### ISSUE TITLE
Use cache in Dockerfiles to speed up builds again

### ISSUE THREAD

**Issue by creydr** [nmstate/kubernetes-nmstate#1031]
**What happened**:
In the Dockerfiles we had `--mount=type=cache,target=/root/.cache/go-build` to speed up the builds: 

https://github.com/nmstate/kubernetes-nmstate/blob/20dc69bdc67eadf915639b907e4faf27f2724a32/build/Dockerfile#L15

https://github.com/nmstate/kubernetes-nmstate/blob/20dc69bdc67eadf915639b907e4faf27f2724a32/build/Dockerfile.operator#L14

Unfortunately the cache type is not supported in Podman < 4.0 and Podman v4 not widely used yet. So we removed this option from the Dockerfiles in #1030.

This issue was created to keep track on the revert on this PR, after Podman v4 got adopted wider.

**What you expected to happen**:
Add `--mount=type=cache,target=/root/.cache/go-build` again (e.g. revert #1030).

**How to reproduce it (as minimally and precisely as possible)**:
Run a `IMAGE_BUILDER=podman make push`

**Comment by qinqon** [comment]
Looks like podman v4.0.0 can be installed with copr at fedora35 https://podman.io/getting-started/installation
```
Podman v4 will [not be shipped](https://podman.io/blogs/2022/03/06/why_no_podman4_f35.html) officially on Fedora 35. However, you can still fetch Podman v4 through our [COPR repo](https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman4/).

sudo dnf -y copr enable rhcontainerbot/podman4
sudo dnf -y install podman
```

Maybe we can re-activate this with a note on the readme
