### ISSUE TITLE
seems outdated replace usage in go.mod

### ISSUE THREAD

**Issue by Morty-luo** [nmstate/kubernetes-nmstate#1147]
It seems that `nmstate/kubernetes-nmstate` at now indirectly depends on exactly `v1.3.2` of `github.com/gogo/protobuf`.
So, it makes no sense to keep according replace directive in go.mod. Should it be dropped? <br>
<https://github.com/nmstate/kubernetes-nmstate/blob/main/go.mod#L53>
```txt
github.com/gogo/protobuf v1.3.2 // indirect
```
<https://github.com/nmstate/kubernetes-nmstate/blob/main/go.mod#L126>
```txt
github.com/gogo/protobuf => github.com/gogo/protobuf v1.3.2
```
Another replace line pins `golang.org/x/text` to `v0.3.7`. However, according to [GO-2022-1059](https://pkg.go.dev/vuln/GO-2022-1059), version of `golang.org/x/text` before `v0.3.8` suffers potential vulnerability. Should it be updated? <br>
<https://github.com/nmstate/kubernetes-nmstate/blob/main/go.mod#L131>
```txt
golang.org/x/text => golang.org/x/text v0.3.7
```

**Comment by qinqon** [comment]
@Morty-luo Can you prepare a fix for it ?

**Comment by Morty-luo** [comment]
Ok, I submitted a PR([#1149](https://github.com/nmstate/kubernetes-nmstate/pull/1149)) which attempts to bump golang.org/x/text to v0.3.8 to fix this issue.

**Comment by qinqon** [comment]
Looks like we have this https://github.com/nmstate/kubernetes-nmstate/pull/1150

**Comment by qinqon** [comment]
Recreating PR again, looks like dependabot is not doing it right
