### ISSUE TITLE
Use go template with cluster-network-addons-operator format for manifests

### ISSUE THREAD

**Issue by qinqon** [nmstate/kubernetes-nmstate#125]
So we can work this https://github.com/kubevirt/cluster-network-addons-operator/issues/178

**Comment by qinqon** [comment]
Let's also investigate https://github.com/hairyhenderson/gomplate so we don't need to maintain some random go code.

**Comment by phoracek** [comment]
@qinqon ha! Look at this.

**Comment by qinqon** [comment]
Let's not introduce another tool, random golang that get compile with go run is good enough.
