### ISSUE TITLE
helm chart for kubernetes-nmstate 

### ISSUE THREAD

**Issue by haiwu** [nmstate/kubernetes-nmstate#1250]
**What happened**:
There's no helm chart for kubernetes-nmstate

**What you expected to happen**:
There should be helm chart for kubernetes-nmstate. 

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
N/A

**Environment**:
N/A

**Comment by qinqon** [comment]
@haiwu this project has already an operator to install it using operator hub https://operatorhub.io/operator/kubernetes-nmstate-operator

We don't have plans to use helm, since it means duplicate the effort.

**Comment by willzhang** [comment]
+1
```
kubectl apply -f https://github.com/nmstate/kubernetes-nmstate/releases/download/v0.82.0/nmstate.io_nmstates.yaml
kubectl apply -f https://github.com/nmstate/kubernetes-nmstate/releases/download/v0.82.0/namespace.yaml
kubectl apply -f https://github.com/nmstate/kubernetes-nmstate/releases/download/v0.82.0/service_account.yaml
kubectl apply -f https://github.com/nmstate/kubernetes-nmstate/releases/download/v0.82.0/role.yaml
kubectl apply -f https://github.com/nmstate/kubernetes-nmstate/releases/download/v0.82.0/role_binding.yaml
kubectl apply -f https://github.com/nmstate/kubernetes-nmstate/releases/download/v0.82.0/operator.yaml

```
Helm installation will be more convenient
```
helm install kubernetes-nmstate repo  -n nmstate
```
