### ISSUE TITLE
Add status conditions to NodeNetworkStatus

### ISSUE THREAD

**Issue by phoracek** [nmstate/kubernetes-nmstate#139]
Let's create a specification of our conditions.

We should be able to expose Success/Failure (with respective error output) in our State section. Since NodeNetworkStatus has two responsibilities - reporting and configuring, we should have separate conditions for both.

This specification should cover list of conditions and matrix with explanation of possible situations.

**Comment by qinqon** [comment]
For sure we need the nmstatectl output on both reporting and configure, but I don't know if this is too long for a k8s CR, also with the addition of temporary fix for vlan_filtering we can have errors executing iproute commands directly.

**Comment by qinqon** [comment]
We implemented Status at NNS
