### ISSUE TITLE
investigate: use a single worker

### ISSUE THREAD

**Issue by yuvalif** [nmstate/kubernetes-nmstate#16]
the controller is handling only a single object (the state for its node) - single threaded handling should be better

**Comment by qinqon** [comment]
So this is the place we workers are started up 
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/internal/controller/controller.go#L155

**Comment by qinqon** [comment]
And looks like by default is one 
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/internal/controller/controller.go#L50

So we are all good here.
