### ISSUE TITLE
Stabilize vlan script

### ISSUE THREAD

**Issue by phoracek** [nmstate/kubernetes-nmstate#184]
The vlan script is a weak point in the configuration. However, there are few things we may do to make it more stable and predictable.

1. Wait for the bridge to become available before we start configuring.
2. Use nmstate rollback mechanism to revert configuration in case the VLAN script fails.

**Comment by phoracek** [comment]
@qinqon ^^

**Comment by qinqon** [comment]
Perfectly put.

**Comment by SchSeba** [comment]
Can we also change it to use the netlink package? 

https://github.com/vishvananda/netlink

**Comment by phoracek** [comment]
@SchSeba does it help with stabilization though? We have a few months left before we get proper VLAN support in nmstate.

**Comment by qinqon** [comment]
Still with netlink rollback is needed since it's not going to be part of the nmstate transaction, my two cents goes to just wait to have it at nmstate.

Also proper way of doing this would be to also do rollback of the vlan filtering, but I don't know if it's worth.
