### ISSUE TITLE
add validating for NodeNetworkState object

### ISSUE THREAD

**Issue by yuvalif** [nmstate/kubernetes-nmstate#2]
- should make sure that only one state object exist per node, and that: object name == node name
- other content validations may also be needed

**Comment by phoracek** [comment]
This can be done either by webhook or CRD OpenAPI check.

**Comment by qinqon** [comment]
Also with less priority validate nmstate date twords [schema](https://github.com/nmstate/nmstate/blob/master/libnmstate/schemas/operational-state.yaml) before it reaches host
