### ISSUE TITLE
Wrong WA sed command used in Dockerfile

### ISSUE THREAD

**Issue by oshoval** [nmstate/kubernetes-nmstate#210]
build/Dockerfile 

RUN sed -i "s/nmclient.NM.DeviceType.OVS_INTERFACE,/nmclient.NM.DeviceType.OVS_INTERFACE, nmclient.NM.DeviceType.BRIDGE,/" /usr/lib/python3.7/site-packages/libnmstate/nm/applier.py

the following line might not do harm, but in case it runs twice 
it will replace again "nmclient.NM.DeviceType.OVS_INTERFACE," 
with "nmclient.NM.DeviceType.OVS_INTERFACE, nmclient.NM.DeviceType.BRIDGE,"
so when the fix of libnmstate present, the line might have types / wrong types

**Comment by qinqon** [comment]
It will not run twice, since result is saved at container layer and not re-run

**Comment by phoracek** [comment]
@qinqon @oshoval we just need to make sure to drop it once we have a fix in nmstate. But even then, it should be harmless if we have the value twice in the list.
