### ISSUE TITLE
Defining an IP address to a bond via NodeNetworkConfigurationPolicy will end in a collision

### ISSUE THREAD

**Issue by yossisegev** [nmstate/kubernetes-nmstate#274]
According to the [bond configuration spec](https://github.com/nmstate/kubernetes-nmstate/blob/master/docs/user-guide-policy-configure-linux-bond.md#configure-bond), you can define an IP address to the bond interface, in spec.desiredState.interfaces[bond entry].ipv4.address.
Deploying the policy will end up in an IP collision, because it will create a bond on each node, with all these bonds having the same IP address.
Possible workaround until it is resolved:
1. Deploying different policy to each node using nodeSelector, with each policy setting a different IP address.
2. Manually setting the IP address of each bond after the policy is applied.

**Comment by phoracek** [comment]
You are right, the example is valid only with a single node in a cluster. We should change the example to use DHCP.
