### ISSUE TITLE
Add a nodeSelector example to the bond configuration tutorial

### ISSUE THREAD

**Issue by yossisegev** [nmstate/kubernetes-nmstate#275]
The [bond configuration tutorial](https://github.com/nmstate/kubernetes-nmstate/blob/master/docs/user-guide-policy-configure-linux-bond.md) currently doesn't have a nodeSelector example, like the ones in the bridge tutorials (e.g in [linux-bridge tutorial](https://github.com/nmstate/kubernetes-nmstate/blob/master/docs/user-guide-policy-configure-linux-bridge.md#selecting-nodes)).

**Comment by phoracek** [comment]
Node selectors are now documented in https://github.com/nmstate/kubernetes-nmstate/blob/master/docs/user-guide-102-configuration.md
