### ISSUE TITLE
Missing keys in slaves list in bond manuals

### ISSUE THREAD

**Issue by yossisegev** [nmstate/kubernetes-nmstate#305]
In both bond manuals - the slaves list is missing the key, which is "name", so the slaves appear as a list of strings rather than a list of dicts:
```
        slaves:
        - eth1
        - eth2
```
while it should be
```
        slaves:
        - name: eth1
        - name: eth2
```
This issue exists in:
1. https://github.com/nmstate/kubernetes-nmstate/blob/master/docs/user-guide-policy-configure-linux-bond.md#configure-bond
2. https://github.com/nmstate/kubernetes-nmstate/blob/master/docs/user-guide-policy-configure-linux-bond-with-vlans.md#configure-bond-with-vlan

**Comment by phoracek** [comment]
Those manuals are correct. With Linux bonding, it is a list of strings (https://nmstate.github.io/examples.html#interfaces-bond) while with OVS, it is a list of objects.
