### ISSUE TITLE
Errors in the logs of nmstate-handler pods

### ISSUE THREAD

**Issue by mardim91** [nmstate/kubernetes-nmstate#398]
**What happened**:

I deployed kube-nmstate by following the arbitrary-cluster instructions. The nmstate-handler pods are up and running but I am seeing this error in the pod's logs:

`github.com/operator-framework/operator-sdk/pkg/kube-metrics/store.go:65: Failed to list *unstructured.Unstructured: the server could not find the requested resource`

**What you expected to happen**:

I expected not to see the above error in the pod's logs

**How to reproduce it (as minimally and precisely as possible)**:

Deploy kubernetes in Ubuntu (bionic-beaver) with kubeadm. Follow the instructions for the deploy of kubernetes-nmstate for the arbitrary cluster. Check the logs of nmstate-handler pods when the pods are deployed.

**Comment by phoracek** [comment]
Hello @mardim91, thanks for reporting this. This issue should be fixed on master via https://github.com/nmstate/kubernetes-nmstate/pull/378 and should disappear once we release a new version of kubernetes-nmstate in cluster-network-addons-operator. I will update this Issue once it is available, so we can verify that it is indeed fixed.

**Comment by mardim91** [comment]
Ok thanks a lot ! @phoracek

**Comment by mardim91** [comment]
@phoracek @qinqon The above error was appearing in a consistent and repeatitive manner in the logs of nmstate-handler and due to that no free disk space has left in my VMs which caused the VMs to pause.

**Comment by qinqon** [comment]
Can you use latest cnao? It has kubernetes-nmstate updated.

**Comment by mardim91** [comment]
@phoracek @qinqon So I deployed with the latest cnao (0.27) and now I am seeing this error in the logs of the nmstate-handler(0.14).

E0217 13:26:57.441523       1 reflector.go:125] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:204: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:cluster-network-addons:nmstate-handler" cannot list resource "configmaps" in API group "" at the cluster scope

**Comment by phoracek** [comment]
Thanks. That's annoying. We need to take a look into it @qinqon

**Comment by phoracek** [comment]
Tackled in https://github.com/kubevirt/cluster-network-addons-operator/pull/296

**Comment by mardim91** [comment]
@phoracek @qinqon I have deployed with the latest cnao image and it seems that the error is gone.

Also I have read that if I want to configure ovs bridges you need to have NetworkManager-ovs plugin installed. Like this: https://reposcope.com/package/NetworkManager-ovs 

Do you know where can I find this plugin for ubuntu? If you do not have the deb package can you please paste the source code repository link and I will build it from source.

Thanks!

**Comment by phoracek** [comment]
I don't really know how they build it, the best place to ask such questions would be https://mail.gnome.org/mailman/listinfo/networkmanager-list

**Comment by mardim91** [comment]
@phoracek ok thanks a lot

**Comment by qinqon** [comment]
@mardim91 In case you find the way, can you open a PR at doc's with it ? Or share it here so we add it for other users ?

Thanks.

**Comment by mardim91** [comment]
@qinqon Yes if I find something usefull I will open the PR.

**Comment by mardim91** [comment]
@qinqon @phoracek In this thread [0] you will find the results of my investigation for the nm-openvswitch plugin in Ubuntu 16.04

[0] https://mail.gnome.org/archives/networkmanager-list/2020-February/msg00016.html

**Comment by phoracek** [comment]
@mardim91 thanks for the investigation. Can we close this issue now?

**Comment by mardim91** [comment]
@phoracek Yes we can close this issue
