### ISSUE TITLE
Strange behaviour when you use node selector

### ISSUE THREAD

**Issue by mardim91** [nmstate/kubernetes-nmstate#409]
**What happened**:

In a three node cluster if I create a resource only for one node by using a node selector it will automatically create three nnce resources One for the actual selector and one for the other two nodes which I didn't choose. Is this normal?

So I used this yaml file to create a bond interface:  https://hastebin.com/onimezovig.bash 

As you can see I have registered a node selector for this. But if I check the nnce entries I see this: 

https://hastebin.com/dujupiduda.rb

It created a nnce for every node that I have.

**Comment by qinqon** [comment]
It creates a nnce for all the nodes independent of node selector, but at the nodes were nodeSelector does not match, conditions would have Matchin as False.

**Comment by mardim91** [comment]
Oh ok. Then this is a normal behaviour then. I will close the issue. Thanks!

**Comment by phoracek** [comment]
@mardim91 we added a new doc series to https://github.com/nmstate/kubernetes-nmstate/#deployment-and-usage. It should guide you through all the features
