### ISSUE TITLE
stp config is mandatory even if stp is disabled

### ISSUE THREAD

**Issue by qinqon** [nmstate/kubernetes-nmstate#45]
when configuring linux bridges even if we set stp enabled: false we still need to set various stp attributes like this                                                           
        bridge:                                                                 
          options:                                                              
            stp:                                                                
              enabled: false                                                    
          port:                                                                 
            - name: eth1                                                        
              stp-hairpin-mode: false                                           
              stp-path-cost: 100                                                
              stp-priority: 32                            

Issue https://github.com/nmstate/nmstate/issues/443

**Comment by phoracek** [comment]
The bug on nmstate has been fixed.
