### ISSUE TITLE
remove iface if not listed anymore

### ISSUE THREAD

**Issue by phoracek** [nmstate/kubernetes-nmstate#48]
https://github.com/nmstate/kubernetes-nmstate/pull/43#discussion_r287724131

I believe that we should remove interfaces that are not listed in NodeNetworkState anymore. Let's discuss it further.

**Comment by qinqon** [comment]
Then we have to first discover them and then include in the DesiredState with "absent" state ? or do you mean changing nmstate all together ?

**Comment by phoracek** [comment]
@EdDev:

> 
> You could implement this logic and use the absent state at the backend only. You can even ask for a special verb on nmstate to do this.
> However, please consider that this will cause a burden on kubernetes-nmstate to manage all the node, instead of managing only what interests the operator/admin.
> It is reasonable for an admin to reserve interfaces or other resources to itself and not let k8s take ownership on them. Even if you will not need this today, and it will appear somewhere in the future, you will have hard time to support it.
> 
> Also, consider that you may want today to ignore specific interfaces all together (like tap, veth and alike), as they are not "owned" by the node, but by the pods.

We don't need to discover them. On NodeNetworkState update we see previous and new configuration. We would just set absent on those interfaces that were present in previous and are not in the new.

Let us keep this issue for a while, I don't want to spend too much time with it now, when we don't have anything really working and used. Once we have real use-cases, we can discuss what would be a better approach.

**Comment by phoracek** [comment]
We decided to follow nmstate's behavior and remove interfaces only upon explicit request.
