### ISSUE TITLE
Calling kubectl delete nncp does not block until all nnce are deleted.

### ISSUE THREAD

**Issue by qinqon** [nmstate/kubernetes-nmstate#486]
**What happened**:
A call to kubectl delete nncp was made but after finishing all the nnce were still there, it took some
time for them to dissappear.

**What you expected to happen**:
All the nnce to be deleted after nncp is deleted.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- `NodeNetworkState` on affected nodes (use `kubectl get nodenetworkstate <node_name> -o yaml`):
- Problematic `NodeNetworkConfigurationPolicy`:
- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`):
- NetworkManager version (use `nmcli --version`)
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by phoracek** [comment]
We can simply set the owner reference to block deletion of nncp until nnces are deleted.

**Comment by qinqon** [comment]
kubectl delete has a "--cascade=foreground." that can be used for this, we can close this.

https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#setting-the-cascading-deletion-policy
