### ISSUE TITLE
SCC namespace is not templated

### ISSUE THREAD

**Issue by phoracek** [nmstate/kubernetes-nmstate#494]
**What happened**:

We forgot to add templating to SCC namespace: https://github.com/nmstate/kubernetes-nmstate/blob/master/deploy/openshift/scc.yaml#L14

**What you expected to happen**:

Namespace should not be hardcoded but taken from a variable.

**Comment by phoracek** [comment]
@bcrochet @qinqon

**Comment by qinqon** [comment]
Fixed
