### ISSUE TITLE
add make docker-push

### ISSUE THREAD

**Issue by yuvalif** [nmstate/kubernetes-nmstate#5]
should push all images to: https://hub.docker.com/u/nmstate/
pod definitions should be updated accordingly (not to pull from yuvalif repo)

**Comment by phoracek** [comment]
images are now hosted on quay.io and their builds are automated.

https://quay.io/repository/nmstate/kubernetes-nmstate-state-handler?tab=info
https://quay.io/repository/nmstate/kubernetes-nmstate-configuration-policy-handler?tab=info
