### ISSUE TITLE
Build Openshift handler image (build/Dockerfile.openshift) fails with error (No package matches nmstate)

### ISSUE THREAD

**Issue by yboaron** [nmstate/kubernetes-nmstate#516]
**What happened**:
Openshift handler image creation fails with error:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
[centos@yossi1 kubernetes-nmstate]$ sudo podman build -f build/Dockerfile.openshift  -t yb  . 
STEP 1: FROM registry.svc.ci.openshift.org/openshift/release:golang-1.13 AS builder
STEP 2: WORKDIR /go/src/github.com/openshift/kubernetes-nmstate
--> Using cache 9a3f1b534d82ea8a7f68eebf91831167fb95495146e010d61b4586030c460414
STEP 3: COPY . .
720537cd42c00e5be6c2f619347fd4c8e47ec018c3a137049121d5d3f21cb2bd
STEP 4: RUN GO111MODULE=on go build --mod=vendor -o build/_output/bin/kubernetes-nmstate cmd/manager/main.go
b13093f3ac95cb95cd893266bc003c3485fac3a3677a6e1cce088940ceff868d
STEP 5: FROM ubi8-minimal
STEP 6: RUN     microdnf -y update &&     microdnf -y install         nmstate         iputils         iproute &&     microdnf clean all

(process:9): librhsm-WARNING **: 10:34:02.438: Found 0 entitlement certificates

(process:9): librhsm-WARNING **: 10:34:02.442: Found 0 entitlement certificates

(process:9): libdnf-WARNING **: 10:34:02.443: Loading "/etc/dnf/dnf.conf": IniParser: Can't open file
Downloading metadata...
Downloading metadata...
Downloading metadata...
Nothing to do.

(process:60): librhsm-WARNING **: 10:34:04.879: Found 0 entitlement certificates

(process:60): librhsm-WARNING **: 10:34:04.881: Found 0 entitlement certificates

(process:60): libdnf-WARNING **: 10:34:04.882: Loading "/etc/dnf/dnf.conf": IniParser: Can't open file
Downloading metadata...
Downloading metadata...
error: No package matches 'nmstate'
Error: error building at STEP "RUN microdnf -y update &&     microdnf -y install         nmstate         iputils         iproute &&     microdnf clean all": error while running runtime: exit status 1
[centos@yossi1 kubernetes-nmstate]$
**Anything else we need to know?**:

**Environment**:

- `NodeNetworkState` on affected nodes (use `kubectl get nodenetworkstate <node_name> -o yaml`):
- Problematic `NodeNetworkConfigurationPolicy`:
- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`):
- NetworkManager version (use `nmcli --version`)
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by yboaron** [comment]
Seems that the root cause is nmstate rpm from AppStream repo is available only with a subscription.

**Comment by qinqon** [comment]
Closing this works now, feel free to open if it breaks again.
