### ISSUE TITLE
[prow] running a postsubmitted test failed with - fatal: Couldn't find remote ref deployment-strategy-recreate

### ISSUE THREAD

**Issue by rmohr** [nmstate/kubernetes-nmstate#567]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

Running a postsubmitted test failed with - fatal: Couldn't find remote ref deployment-strategy-recreate
The failure happened on nmstate/kubernetes-nmstate repo.

Link to the job - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/publish-kubernetes-nmstate/1275716907839787008

**What you expected to happen**:
Shoudn't fail.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
/triage build-officer

This is most likely just a one-time hickup. Let's close it if the  next postsubmit is fine.

**Comment by qinqon** [comment]
This job is running at `deployment-strategy-recreate` kubernetes-nmstate PR, and this is not suppose to happend since the job intention is to push kubernetes-nmstate-handler containers after merge to master and that PR is not merged.

**Comment by qinqon** [comment]
I have /retest the PR and job does not appear anymore looks like it was as the same time prow was being updated.
