### ISSUE TITLE
NMState operator when installed for the first time should deploy daemonset and webhook deployment

### ISSUE THREAD

**Issue by arnongilboa** [nmstate/kubernetes-nmstate#572]
/kind bug
/triage build-officer

**What happened**:

[Fail] NMState operator when installed for the first time [It] should deploy daemonset and webhook deployment 
/tmp/knmstate/kubernetes-nmstate/test/e2e/operator/nmstate_install_test.go:40

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/nmstate_kubernetes-nmstate/571/pull-kubernetes-nmstate-e2e-operator-k8s/1280095118921043968

**Comment by qinqon** [comment]
This is not flaky, there were a defect on the PR, closing.
/close
