### ISSUE TITLE
Add cert rotation variables to Nmstate CR 

### ISSUE THREAD

**Issue by qinqon** [nmstate/kubernetes-nmstate#589]
**What happened**:
The latest kube-admission-webhook library release has some cert rotation "knobs" that we can export as Nmstae CR parameters so they can be changed before instdall.

**What you expected to happen**:
The Nmstate CR to have three new parameters to change cert rotation values.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- `NodeNetworkState` on affected nodes (use `kubectl get nodenetworkstate <node_name> -o yaml`):
- Problematic `NodeNetworkConfigurationPolicy`:
- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`):
- NetworkManager version (use `nmcli --version`)
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by qinqon** [comment]
Since CNAO has cert rotation parameters at NetworkAddonsConfig and in the near future CNAO will install kubenretes-nmstate usin gthe NMState CR we have to include those parameters to the this CRD.

**Comment by phoracek** [comment]
I believe you are right @brutus333. I'm not aware of anybody looking into this now, assigning. Thanks!

/assign @brutus333

**Comment by phoracek** [comment]
For the API, would following schema look good to you?

```yaml
spec:
  selfSignConfiguration:
    caRotateInterval: 168h
    caOverlapInterval: 24h
    certRotateInterval: 24h
    certOverlapInterval: 8h
```

**Comment by brutus333** [comment]
> For the API, would following schema look good to you?
> 
> ```yaml
> spec:
>   selfSignConfiguration:
>     caRotateInterval: 168h
>     caOverlapInterval: 24h
>     certRotateInterval: 24h
>     certOverlapInterval: 8h
> ```

Yes, it is looking fine. I'll take care of it after #802.
