### ISSUE TITLE
Add ovs-bridge port vlan tagging functionality to nmstate

### ISSUE THREAD

**Issue by souhradab** [nmstate/kubernetes-nmstate#604]
**What happened**:
I am using nmstate to adjust OCP node networking state per:
https://docs.openshift.com/container-platform/4.5/virt/node_network/virt-updating-node-network-config.html

I am configuring an ovs-cni bridge for CNV (Kubevirt) VM secondary Multus network connections.  I am adding VLAN sub-interfaces to the ovs-cni bridge.  They are added as ovs system interfaces and appear to operate fine.  I am able to connect VM's to the ovs-cni bridge via Network Attachment Definition that do not have a VLAN specified.  

If I connect my VM's to the ovs-cni bridge via a Network Attachment Definition that DOES have a VLAN specified, then my VM's can communicate with each other on the same ovs-cni, but cannot communicate outside via the vlan sub-interface.  The vlan sub-interface does not accept traffic because it's port is not tagged with the appropriate VLAN on the ovs-cni bridge.   This seems to make sense.

**What you expected to happen**:
That said, I would like for nmstate to allow for specifying the vlan tag for a system port added to the ovs-bridge (example: ovs-vsctl add-port br1 bond0.874 tag=874 -- set interface bond0.874 type=system).  If I configure the tag on the ovs port manually, it works, but of course I would prefer that nmstate does this and manages the configuration

The reason for this request is so that I am able to connect multiple vlan sub-interfaces to the same ovs-cni bridge, AND provide per vlan isolation amongst the ovs-cni bridge ports using nmstate.  

**How to reproduce it (as minimally and precisely as possible)**:
-configure k8s/ocp nodes with Kubevirt/openshift-virtualization.  Ensure Multus is installed.
-trunk VLANs to cluster node physical network interface(s).  I am using two and they are bonded (802.3ad)
-use nmstate to create vlan sub-interface ethX.vlan_id (or bondX.vlan_id) across each cluster node
-use nmstate to create ovs-cni bridge with vlan sub-interface ethX.vlan_id (or bondX.vlan_id) as one of its ports.  nmstate creates this as an ovs system port.
-create a NetworkAttachmentDefinition specifying ovs-cni, the bridge name, and vlan ID
-create a vm and connect its secondary NIC (or make this Multus NIC the primary)to the NetworkAttachmentDefinition.
-power vm
-assign vm IP address on the VLAN
-Initiate ping to system outside the host, like the vlan gateway. 
-with ping going, capture traffic at the node level using tcpdump at the VM veth, and the vlan sub-interface which was added to the ovs-cni bridge.  You should see ARP request from the VM veth, and nothing on the vlan sub-interface
-manually tag the ovs port connected to the vlan sub-interface with the vlan id specified in the NetworkAttachmentDefinition associated with the VM.
-capture traffic at the node level using tcpdump at the VM veth, and the vlan sub-interface which was added to the ovs-cni bridge, and the physdev associated with the vlan sub-interface.  You should see ARP complete and then ping echo and echo replies. 

**Environment**:
-nns affected: all
-nncp affected: all
-kubernetes-nmstate image: registry.redhat.io/container-native-virtualization/kubernetes-nmstate-handler-rhel8@sha256:f17f2ef133df6e985118f3dc21a1d3ef67dc66bd68e7556af7bc2b0c4c68c4b8
-nmcli tool: version 1.22.8-4.el8
-OpenShift Container Platform Server Version: 4.5.2, Kubernetes Version: v1.18.3+b74c5ed
-OpenShift Virtualization 2.4

**Comment by souhradab** [comment]
Came across this, need to test it out, this is from nmstate project itself:  https://github.com/nmstate/nmstate/blob/base/examples/ovsbridge_vlan_port.yml

**Comment by phoracek** [comment]
@souhradab have you got a chance to test it? I believe it should work fine, the question is whether the nmstate API covers all your needs there.

**Comment by phoracek** [comment]
Closing this for not enough info. In case you get to test this again with the latest release and it's still broken, feel free to reopen.
