### ISSUE TITLE
live logs from ginkgo does not appear anymore at e2e-tests

### ISSUE THREAD

**Issue by qinqon** [nmstate/kubernetes-nmstate#607]
**What happened**:
Although Makefile specify `-ginkgo.v` the traces from ginkgo like `STEP` and friends only appear at the end.

**What you expected to happen**:
They should appear as they go so you know where is getting stuck for example.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- `NodeNetworkState` on affected nodes (use `kubectl get nodenetworkstate <node_name> -o yaml`):
- Problematic `NodeNetworkConfigurationPolicy`:
- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`):
- NetworkManager version (use `nmcli --version`)
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by phoracek** [comment]
Scrub: We believe this was fixed
