### ISSUE TITLE
Apply NNCP sequencially on nodes.

### ISSUE THREAD

**Issue by qinqon** [nmstate/kubernetes-nmstate#615]
**What happened**:
Today we apply desired state on all matching nodes at once. This may lead to a downtime (waiting for rollback) in case the config is invalid and all nodes are matching.

**What you expected to happen**:
Change knmstate so it applies config on one node at the time and in case it fails, it stops the rollout.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Possible solutions:
* Alphabetically sort all the enactments: The first one will start configuration, all the other will wait until the enactment that is right before them successfully applies. If it fails, all following enactments should be recursively canceled.
  - **Pros**: Is simple to implement, can resume from restarts
  - **Cons**: ordering nodes alphabetically on name means that it depends on how the nodes are named
* Enhance NNCP status to mark current running node with `runningNode` field: nodes will try to set `runningNode` and if conflict they will reload it if runningNode is empty it means the other node has finish so they will try to set it up and on conflict we go back to retry.
  - **Pros**: It has similar simplicity as orderning alphabetically the nodes but without know about the other nodes
  - **Cons**: We have to change nncp status (maybe is not a bad thing).
* Use leader election mechanism: The current leader will apply the config and after finish release the leadership, next one should check if enactments are at good state if not should cancel applying config and release leadership again.
  - **Pros**: Well known mechanism and generic mechanism.
  - **Cons**: Add a lot of complexity and is not very bullet proof.

Also the feature need to be `opt-out` so by default  is safer but can be configured to be quicker by doing it on parallel (in case of big cluster and not problemtic NNCPs) with a NNCP field like `parallel=true` or the like.

**Environment**:

- `NodeNetworkState` on affected nodes (use `kubectl get nodenetworkstate <node_name> -o yaml`):
- Problematic `NodeNetworkConfigurationPolicy`:
- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`):
- NetworkManager version (use `nmcli --version`)
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by qinqon** [comment]
@rhrazdil @phoracek Let's check for corner cases of possible implementations

**Comment by rhrazdil** [comment]
I like the idea of adding a `runningNode` field to the status, it seems clearer and more focused on point, since we don't need to care about the order.
And since we'll want to deal with timeout and add a to way to opt-out, we will not avoid adding fields to nncp config anyway.

**Comment by qinqon** [comment]
@phoracek do you agree with the idea ?

**Comment by phoracek** [comment]
Sounds good. Our own tiny leadership election that we have under control.

But what happens when a user updates a policy? Say I'm in a middle of configuration, I changed my mind and disable DHCP on the policy. What would happen then?

**Comment by qinqon** [comment]
If we wait inside the `Reconcile` the update will be queued.

**Comment by phoracek** [comment]
By updating of the policy, I would remove the `runningNode` attribute as well. That means that some node can start reconfiguration while the configuration on a previous one who set `runningNode` is not yet done. But maybe that's not an issue.

I'd like to see a diagram explaining this mechanism and talking about all the corner-cases such as the one I described. Based on this we would be able to write a test plan and hopefully be able to implement it without surprises coming along the way making this solution way more complex than was anticipated.

**Comment by qinqon** [comment]
Agree, let's list them and think about this.

**Comment by qinqon** [comment]
Another option is to use the webhook and discard NNCP change if is in progress, at the end is what webhooks are for.

**Comment by phoracek** [comment]
But then the handler that has configuration in process will write back. And how would the webhook then see if it is getting written by the old version of NNCP or the new one.

**Comment by rhrazdil** [comment]
I have created this doc where we can discuss the logic for the sequential node update.
There is also a draft of a diagram changes 
https://docs.google.com/document/d/1C8RsopeQ0lTkQunbtOHzbHOuK_hsmg8vX2KudHoFv9Q

> By updating of the policy, I would remove the runningNode attribute as well. That means that some node can start reconfiguration while the configuration on a previous one who set runningNode is not yet done. But maybe that's not an issue.

Hmm... Having two nodes running in parallel in this case is probably not the end of the world, but it's a bit weird and it could make the debugging difficult. What if we added a new resource, say a configMap for these internal purposes?

**Comment by phoracek** [comment]
Issue with that would be that we would introduce a single point of failure.

Would it be ok if we focused now on rollout - if a policy fails on one node, don't attempt on another. And later add sync mechanism making sure that we are tinkering with a single node at the time? I feel these two features can be untangled quite nicely.

Assuming most people configure a single NNCP anyway, locking the whole cluster won't make a difference for them.

**Comment by rhrazdil** [comment]
> Issue with that would be that we would introduce a single point of failure.

Isn't storing this information in nncp spec the same thing?

**Comment by qinqon** [comment]
> But then the handler that has configuration in process will write back. And how would the webhook then see if it is getting written by the old version of NNCP or the new one.

Handle write back the status not the desiredState, I think we can skip status changes at webhooks, at the end the idea is to NNCP changes until they are finished.

**Comment by qinqon** [comment]
> I have created this doc where we can discuss the logic for the sequential node update.
There is also a draft of a diagram changes
https://docs.google.com/document/d/1C8RsopeQ0lTkQunbtOHzbHOuK_hsmg8vX2KudHoFv9Q

Maybe is time to start a github wiki with this things or even a github webpage.

**Comment by phoracek** [comment]
> > Issue with that would be that we would introduce a single point of failure.
> 
> Isn't storing this information in nncp spec the same thing?

That makes it single point of failure only for the specific NNCP. So worst case, we can recover simply by deleting it and creating a new one.
