### ISSUE TITLE
Intermitent Status at NNCP sequencial rollout

### ISSUE THREAD

**Issue by qinqon** [nmstate/kubernetes-nmstate#644]
**What happened**:
When a NNCP is apply without `parallel` or with `parallel: false` field the Status is intermitent.

**What you expected to happen**:
Steady NNCP Status

**How to reproduce it (as minimally and precisely as possible)**:
Apply a NNCP without parallel fields at multi node cluster. 

**Anything else we need to know?**:
This is caused probably by the Reset done at every Reconcile cycle, in sequencial rollout is more apparent since al reset will be done sequencially. One possible fix is in case of sequencial rollout reset only at the first node.

**Environment**:

- `NodeNetworkState` on affected nodes (use `kubectl get nodenetworkstate <node_name> -o yaml`):
- Problematic `NodeNetworkConfigurationPolicy`:
- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`):
- NetworkManager version (use `nmcli --version`)
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by phoracek** [comment]
Scrub: This is partially fixed now via https://github.com/nmstate/kubernetes-nmstate/pull/648 but there are still some loose ends.

**Comment by rhrazdil** [comment]
This should be now fixed completely by https://github.com/nmstate/kubernetes-nmstate/pull/982
