### ISSUE TITLE
[flaky CI] [nns] NNS LastSuccessfulUpdateTime when network configuration hasn't change should not be updated

### ISSUE THREAD

**Issue by qinqon** [nmstate/kubernetes-nmstate#670]
**What happened**:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/nmstate_kubernetes-nmstate/661/pull-kubernetes-nmstate-e2e-handler-k8s/1341025954180370432

```

[nns] NNS LastSuccessfulUpdateTime when network configuration hasn't change should not be updated expand_less | 15s
-- | --
/tmp/knmstate/kubernetes-nmstate/test/e2e/handler/nns_update_timestamp_test.go:29 Failed after 0.006s. Expected     <string>: NodeNetworkStateStatus to match fields: { .CurrentState: 	Expected 	    <string>: "...on: fd10:24..." 	to equal               \| 	    <string>: "...on: fe80::/..." .LastSuccessfulUpdateTime: 	Expected 	    <v1.Time>: { 	        Time: 2020-12-21T14:32:38Z, 	    } 	to equal 	    <v1.Time>: { 	        Time: 2020-12-21T14:32:33Z, 	    } }


```

/kind bug
/triage build-watcher

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- `NodeNetworkState` on affected nodes (use `kubectl get nodenetworkstate <node_name> -o yaml`):
- Problematic `NodeNetworkConfigurationPolicy`:
- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`):
- NetworkManager version (use `nmcli --version`)
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by nelsonspbr** [comment]
Again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/nmstate_kubernetes-nmstate/692/pull-kubernetes-nmstate-e2e-handler-k8s-future/1356945962311880705

**Comment by qinqon** [comment]
The diff on states
https://github.com/nmstate/kubernetes-nmstate/pull/688

**Comment by xpivarc** [comment]
Again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/nmstate_kubernetes-nmstate/688/pull-kubernetes-nmstate-e2e-handler-k8s/1358701024306532352
