### ISSUE TITLE
Node controller predicate does not filter at watcher

### ISSUE THREAD

**Issue by qinqon** [nmstate/kubernetes-nmstate#684]
**What happened**:
At big clusters every handler is retrieving all the nodes and that hits hard the kube-apiserver nodes.
**What you expected to happen**:
controller-runtime filtering using predicates so it retrieves only the ones filetered.

**How to reproduce it (as minimally and precisely as possible)**:
Counting the number of Node Get operations at running kubernetes-nmstate.

**Anything else we need to know?**:
This is a bug at controller-runtime  this is a bug at controller-runtime https://github.com/kubernetes-sigs/controller-runtime/issues/244.

**Environment**:

- `NodeNetworkState` on affected nodes (use `kubectl get nodenetworkstate <node_name> -o yaml`):
- Problematic `NodeNetworkConfigurationPolicy`:
- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`):
- NetworkManager version (use `nmcli --version`)
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by phoracek** [comment]
It does filter it there now!
