### ISSUE TITLE
Current Gateway Getting Reconfigured by NetworkManager

### ISSUE THREAD

**Issue by MarkSpencerTan** [nmstate/kubernetes-nmstate#714]
**What happened**:

Whenever we're applying NNCP configuration, whether setting them to "up" or "absent" for linux-bridge interfaces, for some reason we notice that our main interface & Default Gateway (team0) is getting reconfigured by NetworkManager. I was wondering if nmstate is doing something strange here and why it's doing that.

When tailing /var/log/messages on the node we see this error:

```bash
Mar  9 15:12:33 vrack-w1 NetworkManager[1579]: <info>  [1615331553.0485] audit: op="checkpoint-create" arg="/org/freedesktop/NetworkManager/Checkpoint/3098" pid=752568 uid=0 result="success"
Mar  9 15:12:33 vrack-w1 NetworkManager[1579]: <info>  [1615331553.0670] audit: op="connection-update" uuid="47b7fa93-1abb-4474-a748-e6c48483509c" name="team0" args="ipv4.gateway,ipv6.dhcp-iaid,ipv6.addr-gen-mode,ipv6.dhcp-duid" pid=752568 uid=0 result="success"
```
We aren't sure where that `connection-update` is coming from.

**What you expected to happen**:

bridge comes up successfully without it touching team0 interface

**How to reproduce it (as minimally and precisely as possible)**:

1. Apply Linux Bridge NNCP configuration
2. View /var/log/messages on the Node

**Anything else we need to know?**:

**Environment**:

- Problematic `NodeNetworkConfigurationPolicy`:
```yaml
apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: mark-bridge-remove
spec:
  desiredState:
    interfaces:
    - name: markbr
      state: up
      type: linux-bridge
```
- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`): v0.21.0 (Tested it on v0.34.0 as well with the new DHCP polling and same behavior)
- NetworkManager version (use `nmcli --version`): nmcli tool, version 1.22.8-5.el8_2
- Kubernetes version (use `kubectl version`): v1.17.13
- OS (e.g. from /etc/os-release): CentOS Linux 8 (Core)

**Comment by qinqon** [comment]
Can you test on kubernets-nmstate v0.37.0 it's using nmstate 0.3.z while v0.34.0 is using nmstate 0.2.z

**Comment by MarkSpencerTan** [comment]
Thanks @qinqon , does this new version depend on a new version of NetworkManager/libnm? I tried updating to this version on our dev cluster but it throws an error everytime an NNCP is applied complaining about a version mismatch between NetworkManager and linnm

**Comment by qinqon** [comment]
@MarkSpencerTan it needs NetworkManager 1.26 https://github.com/nmstate/kubernetes-nmstate/blob/master/Makefile#L8

**Comment by MarkSpencerTan** [comment]
@qinqon I've tested on the current latest version of Kubernetes nmstate as well as version 1.31.0 of NetworkManager on the nodes and this issue is still happening.

We've also started moving our infrastructure to AWS and we're currently using an EKS cluster now and we were able to reproduce the same scenario in this cluster as well. Seems like kubernetes-nmstate doesn't play around very well with clusters with private subnets where there's no default gateway with internet? 

I saw there was a change involving a dns check implemented in addition, however, it was also failing on this cluster. From the looks of it, if both of those fails it does a rollback on the network configuration which for some reason messes with the main interface we're using. I need to basically reboot the node to put things back in the same state as before. 

Are there any options for us for our cluster in a private subnet that doesn't have a gateway to ping and a dns to probe? We don't want the rollback to happen since it's seemingly causing issues with the networking.

**Comment by qinqon** [comment]
kuberbetes-nmstate is suppose to run the probes that were working before network reconfiguration, so if ping gw or resolv DNS probes does not work they will not be executed after reconfiguration.

**Comment by phoracek** [comment]
@MarkSpencerTan sorry for your trouble. In order to debug this effectively, we will need following:

- Logs of the nmstate-handler of the affected node
- `oc get nns <affected host> -o yaml` before you run the configuration
- `ip address` on the host before you run the config
- `ip route` on the host before you run the config
- `nmcli` on the host before you run the config
- `oc get nnce <enactment of given policy and host> -o yaml` after the failure

**Comment by MarkSpencerTan** [comment]
Thank you @qinqon  and @phoracek for the assist! here are some logs from our cluster below:

I updated the specs of our Node to make sure we're working with more up to date components
Node OS: Ubuntu 20.04.2
NetworkManager Version: 1.22.10
Kubernetes-NMState Version: v0.45.0
Kubernetes: v1.18.9


- Logs of the nmstate-handler of the affected node
- https://gist.github.com/MarkSpencerTan/39b7998a4490d1a5625b5d694f7a9b84
- oc get nns <affected host> -o yaml before you run the configuration
   https://gist.github.com/MarkSpencerTan/d44832c5ab8745d8548f9f8a1c0d2536
- ip address on the host before you run the config
   https://gist.github.com/MarkSpencerTan/0ddef23a4bd98df7fd57063ada77c6ef
- ip route on the host before you run the config
   https://gist.github.com/MarkSpencerTan/b1f28362abed576f32873a05806d4e2f
- nmcli on the host before you run the config
   https://gist.github.com/MarkSpencerTan/1490aedf977677138221b792d3c51306
- oc get nnce <enactment of given policy and host> -o yaml after the failure
  https://gist.github.com/MarkSpencerTan/e2b68cf09426fa43d0b98fc87975018a
- nmstate-handler after applying nncp
  https://gist.github.com/MarkSpencerTan/e638980a9f72cc43cbe54edb11dbb077

**Comment by MarkSpencerTan** [comment]
@rhrazdil thank you for the suggestions! 

I followed the extra step here for ubuntu nodes: https://github.com/nmstate/kubernetes-nmstate/blob/master/CONTRIBUTING.md#FAQ and I believe that fixed the nmcli output showing unmanaged for all... now I see a couple that connected successfully: 
https://gist.github.com/MarkSpencerTan/a50b45a9fe5e14010974ec6cab42d3a0
Does that look better?

Thanks for reminding me, I forgot to update NetworkManager as mentioned above and when I installed v1.31.0 for this newer ubuntu node, I was able to pass the probe errors when applying an nncp to set an interface to 'absent' state! However, the 'up' state are failing for some odd reason. I've tried to bring up a simple ethernet, linux bridge, and vxlan and same result.

nncp.yaml: 
```yaml
apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: nncp-clean-test
spec:
  desiredState:
    interfaces:
    - name: marketh
      type: ethernet
      state: up
```
nmstate-handler log:
https://gist.github.com/MarkSpencerTan/ca304c83c2b694b539ede35e5a9297d6
nnce fail log:
https://gist.github.com/MarkSpencerTan/318fad2e8173d1a7da9c19cd7b738d4c

Looks like it's timing out on creating the profile?

**Comment by MarkSpencerTan** [comment]
hmm I think it might be actually how I'm installing the new NetworkManager on top of the one already existing in the OS... I was just building it from the source from git and then moving the built NetworkManager binary over to the /usr/local/sbin directory. I think there were some steps that I might have missed for installing NetworkManager from source since from the NetworkManager's service logs using journalctl there were some permission errors. Do you guys by any chance know any docs or steps on how to install it from source so I can make sure it's being installed correctly?

**Comment by rhrazdil** [comment]
> https://gist.github.com/MarkSpencerTan/a50b45a9fe5e14010974ec6cab42d3a0
Does that look better?

Good. Yes, this is more of an expected output.

> Thanks for reminding me, I forgot to update NetworkManager as mentioned above and when I installed v1.31.0 for this newer ubuntu node, I was able to pass the probe errors when applying an nncp to set an interface to 'absent' state! However, the 'up' state are failing for some odd reason. I've tried to bring up a simple ethernet, linux bridge, and vxlan and same result.

I have to admit I'm getting a bit out of my comfort zone when it comes to building NetworkManager from source on Ubuntu.
If I'm looking correctly though, there seems to be 1.26.2 package available in ubuntu groovy repository:
https://packages.ubuntu.com/source/groovy/network-manager
Maybe that would be good enough?

> nmstate-handler log:
https://gist.github.com/MarkSpencerTan/ca304c83c2b694b539ede35e5a9297d6
nnce fail log:
https://gist.github.com/MarkSpencerTan/318fad2e8173d1a7da9c19cd7b738d4c

The errors there don't look good. Unfortunately, I'm not sure what can we do at kubernetes-nmstate, as we merely delegate the desiredState to nmstate to actually apply it. 

To isolate the issue, it would help if you could try installing `nmstatectl` on your node and tried running `nmstatectl apply` with your desired state: 

```
cat <<EOF > nncp.yaml
interfaces:
- name: marketh
  type: ethernet
  state: up
EOF

nmstatectl apply nncp.yaml
```

According to the [installation guide](https://nmstate.io/user/quick_guide.html), cloning the project and pip install should be all that's needed to install `nmstatectl`
```
git clone https://github.com/nmstate/nmstate.git
cd nmstate
pip install --user --upgrade
```

**Comment by phoracek** [comment]
Closing for the lack of info. Feel free to re-open.
