### ISSUE TITLE
Failed to modify existing bridge with different ports. remove a port and add  a new one

### ISSUE THREAD

**Issue by nabbas-ca** [nmstate/kubernetes-nmstate#727]
**What happened**: I'm trying to update the network configuration of IPI install of openshift on baremetal. I have 2 ports, that I would like to bond, however, at installation time I can only configure provisioning network on one and baremetal network on the other, according to this doc https://openshift-kni.github.io/baremetal-deploy/4.6/Deployment.html . 

I created a policy, where i add a bond interface, enslaving the 2 ports (ens1f0np0 and ens1f1np1) , created a vlan interface on top of the bond, and updated the bridge br-ex to use the newly created bond as its port. I put the policy below in the questions section.

**What you expected to happen**:
I expect that the bond0, bond0.4091 will be created and the bridge will be updated to use the bond0 as its port. 

**How to reproduce it (as minimally and precisely as possible)**:
1- Install openshift on baremetal nodes, with 2 network ports, 1 with provisioning network, 1 with baremetal network
2- create and apply policy  below

**Anything else we need to know?**:
I understand that the ipv4 will be unreachable after the configuration change. I plan to update the switch connected to reflect the change after. 

If there is a better way to do what I'm trying to do, I'm all ears. The main issue is that openshift doesn't support changing or setting the network configuration at install time. They recommend using this operator on Day2 to change the network. 
Error attached here
[nnce-ru5.txt](https://github.com/nmstate/kubernetes-nmstate/files/6330612/nnce-ru5.txt)

**Environment**:
- baremetal IPI install of Openshift with 6 nodes, 2 network ports each. With provisioning network used. 

- `NodeNetworkState` on affected nodes (use `kubectl get nodenetworkstate <node_name> -o yaml`): 
[nns-ru5.txt](https://github.com/nmstate/kubernetes-nmstate/files/6330615/nns-ru5.txt)

- Problematic `NodeNetworkConfigurationPolicy`: 
[bond0-ru5.txt](https://github.com/nmstate/kubernetes-nmstate/files/6330616/bond0-ru5.txt)

- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`):registry.redhat.io/container-native-virtualization/kubernetes-nmstate-handler-rhel8@sha256:6bd5e213988623ba10cafbf4be7436b79aa1545cbe98c8a481437d7db065b333
- NetworkManager version (use `nmcli --version`): nmcli tool, version 1.26.0-14.1.rhaos4.7.el8
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1-5-g76a04fc", GitCommit:"c8d1f56fb3e20d7ee2b4e0280425ef95a013e9ee", GitTreeState:"clean", BuildDate:"2021-03-20T23:43:28Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+bafe72f", GitCommit:"bafe72fb05eddc8246040b9945ec242b9f805935", GitTreeState:"clean", BuildDate:"2021-03-14T16:01:39Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from /etc/os-release):
Red Hat Enterprise Linux CoreOS release 4.7
- Others:

**Comment by qinqon** [comment]
Looks like there is an issue at the NNCP yaml
```
AttributeError: 'bool' object has no attribute 'items'
```

**Comment by qinqon** [comment]
Also openshift is the "owner" of "br-ext" admins should not touch it, if something need to be done with that it has to be done at "day 1" using ignition or the like.

**Comment by phoracek** [comment]
@nabbas-ca did the comment above help you?
