### ISSUE TITLE
node selector labels cannot be more than 63 characters

### ISSUE THREAD

**Issue by qinqon** [nmstate/kubernetes-nmstate#753]
**What happened**:
When an NNCP is populated with nodeSelector labels bigger or equal to 63 characters the NNCE's dos not get created and NNCP not applied.

**What you expected to happen**:
Webhook validating the NNCP node selector or at least NNCP conditions showing the error.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- `NodeNetworkState` on affected nodes (use `kubectl get nodenetworkstate <node_name> -o yaml`):
- Problematic `NodeNetworkConfigurationPolicy`:
- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`):
- NetworkManager version (use `nmcli --version`)
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by phoracek** [comment]
Failing early is definitely and improvement. However, it does not solve the root of this issue. If somebody uses very long node names, it would be impossible to use knmstate. Should we revisit the naming of NNCE and use a prefix taken from NNCP and complete it with a random suffix (similar to pods that are a part of a deployment)? To keep the NNCE list nice, we can keep NNCE and Node names as metadata and print them in separate columns of `kubectl get nnce`.

**Comment by phoracek** [comment]
Oh my bad, never mind.

**Comment by dankenigsberg** [comment]
What does other resources do in case they have a `nodeSelector` field? I personally dislike validations - it forces knmstate to know what is the limitation of the current k8s version. It's a violation of layering. I would rather see a status message explaining as much as we can guess why the operation does not progress.

**Comment by qinqon** [comment]
> What does other resources do in case they have a `nodeSelector` field? I personally dislike validations - it forces knmstate to know what is the limitation of the current k8s version. It's a violation of layering. I would rather see a status message explaining as much as we can guess why the operation does not progress.

Well we are using the k8s golang lib for the validation os kubernetes-nmstate is not copy-pasting the validations done at k8s, also doing failfast is better IMHO.

**Comment by dankenigsberg** [comment]
Even if you vendor k8s's validation, it would break the layering. If next k8s version changes the max to 64 chars, knmstate would become over-restrictive until you re-vendor and re-compile it.

Do other higher-level resources do this validation? There are uncountable modes of failure, we can never block them all precisely; I think we should invest in exposing the reason of failure to the end user - whatever it may be.

Don't get me wrong - I'm only expressing my layman's opinion.

**Comment by qinqon** [comment]
but thinking about it, since webhook are optional at kubernetes-nmstate we should do better showing the error at NNCP Status.
