### ISSUE TITLE
Add NetworkManager and nmstate version to NodeNetworkState Status

### ISSUE THREAD

**Issue by qinqon** [nmstate/kubernetes-nmstate#767]
**What happened**:
Sometimes is good to know what nmstate and NetworkManager versions kubernetes-nmstate is dealing with

**What you expected to happen**:
The NetworkManager an nmstate versions to appear under NodeNetworkState Status

* host NetworkManager version
* container libnm
* container nmstate

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- `NodeNetworkState` on affected nodes (use `kubectl get nodenetworkstate <node_name> -o yaml`):
- Problematic `NodeNetworkConfigurationPolicy`:
- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`):
- NetworkManager version (use `nmcli --version`)
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by brutus333** [comment]
@phoracek : I believe I can take this one. Would you be so nice and assign it to me?

**Comment by phoracek** [comment]
Hello @brutus333. Thanks for the volunteering spirit. This has been already taken by @tompsota, but I forgot to make this assigned, that's totally my bad, sorry about it. Would you see if one of the other open Issues look interesting to you? If none seems fitting, I'd try to try to figure out something new.

/assign @tompsota

**Comment by brutus333** [comment]
@phoracek : No problem, I'll look after something else.
