### ISSUE TITLE
Run per-node

### ISSUE THREAD

**Issue by phoracek** [nmstate/kubernetes-nmstate#78]
In order to avoid connectivity issues, we should run per node. After we get our current PRs merged, let's follow:

- [x] Remove leader election and run tests again, when executed on a single node, it should still pass
- [x] Share a single container between operator and nmstatectl, drop exec logic and just call it locally
- [x] Add selector reconciling only local node

With this change, we should avoid problems with connectivity lost and execution synchronisation.

**Comment by qinqon** [comment]
Would be nice to fix #52 so we can test with multiple nodes, now that we have a distributed handler is makes more sense.
