### ISSUE TITLE
Custom tolerations for the nmstate-handler DaemonSet 

### ISSUE THREAD

**Issue by hubwoop** [nmstate/kubernetes-nmstate#789]
**What happened**: The Pods of the nmstate-handler DaemonSet are not rolled-out on every node on my cluster, because we have set up taints on some nodes.

**What you expected to happen**: I would like to be able to define custom tolerations for the nmstate-handler Daemon-Set

**How to reproduce it (as minimally and precisely as possible)**: 
1. Taint a node
2. Deploy kubernetes-nmstate
3. Watch as the pods of nmstate-handler are not rolled out on tainted nodes.

**Anything else we need to know?**: nope. Great Operator!

**Environment**: We are running OpenShift 4.7 but that shouldn't matter in this case I guess. 
Operator Version: 4.7.0-202106090743 provided by Red Hat, Inc

**Comment by phoracek** [comment]
Hello @hubwoop, thanks for reporting this.

I think this should not be too difficult to adjust. We would need to extend the API https://github.com/nmstate/kubernetes-nmstate/blob/main/api/v1beta1/nmstate_types.go#L25 and then extend this section based on it https://github.com/nmstate/kubernetes-nmstate/blob/main/controllers/nmstate_controller.go#L178.

I can't make a commitment on when this would be available, but it should be fairly easy to implement. If this is something you would be willing to take, I would be more than happy to assist you.

**Comment by brutus333** [comment]
Hello! I'd like to take this one, it seems to be quite easy. 

The only question I have is related to schema versioning: should I keep the change on v1beta1 schema or should I introduce a new version for it (it shouldn't be a required step but it's better to ask)?

**Comment by phoracek** [comment]
Awesome!

Since this new field does not break backwards compatibility, we can (and should) reuse the same version.

Let me know if you'd need assistance with anything.

**Comment by brutus333** [comment]
It seems it was already solved via: https://github.com/nmstate/kubernetes-nmstate/pull/755 (but not released yet: https://github.com/nmstate/kubernetes-nmstate/blob/release-0.47/controllers/nmstate_controller.go#L175).
How do you advise to proceed further with this issue?

**Comment by phoracek** [comment]
Correct me if I'm wrong, but I believe the linked PR changed the default toleration, while the request of this RFE is to make it configurable - so we should make it possible to override the default by setting a new attribute in NMState object.

**Comment by brutus333** [comment]
Yes, you're right with one small difference I believe: the linked PR changed the default toleration to allow any taint while the issue was reported for a code version which did not let daemonset pods running on nodes with custom taints.
Of course we can implement custom tolerations but in this case we need to agree to change the behavior when custom tolerations are provided: instead of putting the pods on all nodes we will only allow the ones from the custom tolerations.
In my view, comparing to current code in main/master branch, this will be an opt-out behavior instead of opt-in (what @hubwoop required).
Please tell me if I'm wrong

**Comment by phoracek** [comment]
Oh, understood. Good catch!

@hubwoop your specific issue will be likely resolved in the next release as long as it brings one of the newer builds.

@brutus333 would following make sense? "By default, nmstate will be deployed on all nodes. This behavior can be changed through nodeSelector/toleration ... attributes on the NMState CR"

**Comment by phoracek** [comment]
@qinqon @rhrazdil FYI ^^

**Comment by brutus333** [comment]
> Oh, understood. Good catch!
> 
> @hubwoop your specific issue will be likely resolved in the next release as long as it brings one of the newer builds.
> 
> @brutus333 would following make sense? "By default, nmstate will be deployed on all nodes. This behavior can be changed through nodeSelector/toleration ... attributes on the NMState CR"

Yes, it would make sense.
