### ISSUE TITLE
OVS not running on debian/ubuntu

### ISSUE THREAD

**Issue by soessa** [nmstate/kubernetes-nmstate#805]
**What happened**:
I have installed nmstate in my kubernetes cluster after compiling and building Network Manager on my node. With nmcli, I can deploy OVS-bridges without an issue but when I try to create nncp, nmstate returns the error "openvswitch is not running" while ovs actually is on my node.

**What you expected to happen**:
Creation of the nncp/nnce and deployment of my ovs bridges and ports.

**How to reproduce it (as minimally and precisely as possible)**:
Compile and build Network Manager on debian/ubuntu, install nmstate and try to deploy a basic ovs set up. 

**Anything else we need to know?**:
On debian/ubuntu, ovs service isn't openvswitch.service but openvswitch-switch.service and it seems that nmstate runs systemctl status openvswitch instead of systemctl status openvswitch-switch to check wether ovs is running or not. 

**Environment**:
- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`): quay.io/nmstate/kubernetes-nmstate-handler@sha256:173ba08e3f9974656cb5a64288dbe3af372ba32a032dc33912c64186cee34a7d
- NetworkManager version (use `nmcli --version`): 1.33.1

**Comment by phoracek** [comment]
Hello @soessa. This seems to be a problem in the underlying nmstate tool. Would you mind opening an Issue directly on https://github.com/nmstate/nmstate/? I believe it will have to be solved there.

**Comment by mel1nn** [comment]
Hi, this problem has been solved in the 1.1.0 version of nmstate. I suppose that a new kubernetes-nmstate-handler image should be built with this latest version, am I right ?
Thanks

**Comment by phoracek** [comment]
@mel1nn was nmstate 1.1.0 released? The latest version I found on Copr was 1.0: https://copr.fedorainfracloud.org/coprs/nmstate/nmstate/packages/. Once a new release is tagged, I believe we can start consuming it. Our CI is continuously testing with their latest builds.
