### ISSUE TITLE
[RFE] Extract nmstate API schema into a dedicated repository

### ISSUE THREAD

**Issue by phoracek** [nmstate/kubernetes-nmstate#864]
**What happened**:

Due to the API being a part of this repository, anybody who wants to vendor it into their project can suffer a dependency hell. As there are new nmstate API based projects being created, written in Go, this becomes a problem.

**What you expected to happen**:

The API schema should be extracted to a dedicated repository.

**Comment by filanov** [comment]
It doesn't need to be a dedicated repo, maybe just a different sub-module https://github.com/go-modules-by-example/submodules

**Comment by filanov** [comment]
example from hive https://github.com/openshift/hive/tree/master/apis

**Comment by phoracek** [comment]
Thanks @filanov that helps o/

**Comment by filanov** [comment]
Hey @phoracek opened https://github.com/nmstate/kubernetes-nmstate/pull/878

**Comment by filanov** [comment]
This issue can be closed :)

**Comment by phoracek** [comment]
Thanks @filanov, great stuff!

https://github.com/nmstate/kubernetes-nmstate/pull/911
