### ISSUE TITLE
Add e2e test connecting ovs-bridge with default NIC and linux-bridge via veth

### ISSUE THREAD

**Issue by rhrazdil** [nmstate/kubernetes-nmstate#875]
> We'll want to extend our e2e test with a scenario that creates ovs-bridge with primary nic connected to it as a port as well as a veth pair connecting linux-bride to the ovs-bridge.
However, this is currently blocked by an nmstate bug that causes removing ovs-bridge to fail (sometimes).
Let's include this scenario when https://bugzilla.redhat.com/show_bug.cgi?id=2012420 is resolved

See https://github.com/nmstate/kubernetes-nmstate/pull/861#issuecomment-966324753

**Comment by qinqon** [comment]
It's about adding an example and integration tests.
