### ISSUE TITLE
use x-kubernetes-validations for CRD field validations if possible

### ISSUE THREAD

**Issue by rhrazdil** [nmstate/kubernetes-nmstate#978]
**What happened**:

K8S has a feature that allows specifying field constrains in CRD definition.
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#wg-odf-sre-validation

We could use this feature and get rid of some of our webhookd, that currently take care of validation the fields.

**Comment by qinqon** [comment]
We close this issue, @tompsota gave good reasons.
